### ISSUE TITLE
Boolean pattern match evaluates incorrectly

### ISSUE THREAD

**Issue by siddharth-krishna** [plow-technologies/inferno#64]
```ocaml
match 1 < 2 with {
  | #false -> 1.1
  | #true -> 0.0
}
```
Evaluates to `1.1` but it should be `0.0`.

**Comment by siddharth-krishna** [comment]
@goodlyrottenapple I think the issue is in the `eval` code for enums, it is comparing the hash of the value and the pattern, 
https://github.com/plow-technologies/inferno/blob/53454aba2ef76b2c08ee6c031a710b4551759d7a/inferno-core/src/Inferno/Eval.hs#L218-L224
but I think both `#true` and `#false` have the same hash. Should I change the eval code to compare the `Ident`s instead?
https://github.com/plow-technologies/inferno/blob/53454aba2ef76b2c08ee6c031a710b4551759d7a/inferno-core/test/Eval/Spec.hs#L368-L370

**Comment by goodlyrottenapple** [comment]
oof, yes. i think its meant to be 

```haskell
(VEnum h1 i1, PEnum _ (Just h2) i2 _) -> 
     if h1 == h2 && i1 == i2
       then Just mempty 
       else Nothing 
```
