### ISSUE TITLE
Torch version mismatch

### ISSUE THREAD

**Issue by antonioc76** [plow-technologies/inferno#65]
As far as I can tell, Nix is not grabbing the version of pytorch specified here: https://github.com/plow-technologies/inferno/blob/8d1a5eee65fab73afc28c185199b44ece9b97b30/.github/workflows/build.yml#L50-L51.

**Comment by antonioc76** [comment]
@smurphy8 @ngua

**Comment by ngua** [comment]
@antonioc76 That is pulling Pytorch from PyPI, not via Nix

**Comment by ngua** [comment]
@antonioc76 Why do think it's the wrong version? We need compatibility with Hasktorch, which works with `torch` version 1.11. Or is it another dependency that's incorrect?

**Comment by ngua** [comment]
Oh, perhaps I misunderstood your comment. Do you mean that the version of `torch` and related is not the same as the one specified in CI (meaning that CI is correct, but the Nix versions are not)?

**Comment by ngua** [comment]
@antonioc76 You are correct, the `devShells..pytorch` has the wrong versions (it's one major version too high)

**Comment by smurphy8** [comment]
Thanks @ngua !
